# version: '3.8'

services:
  db:
    image: postgres:15 # Docker HubからPostgreSQLのバージョン15の公式イメージを使用
    container_name: meal-tracker-db
    restart: always
    environment:
      - POSTGRES_USER: ${POSTGRES_USER}
      - POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      - POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  
  backend:
    build: ./backend
    container_name: meal-tracker-backend
    ports:
      - "8000:8000"
    depends_on:
      - db
  
  frontend:
    build: ./frontend
    container_name: meal-tracker-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db-data: